### ISSUE TITLE
More JS Minification

### ISSUE THREAD

**Issue by mirkosertic** [mirkosertic/Bytecoder#118]

**Comment by WhiteHexagon** [comment]
back again :)  I can see that you previously did some work on the javascript size.  And currently I dont see an issue with a 11KB file, however looking at the 'bytecoder_wasmbindings.js' file there seems to be an opportunity to minify this some more at generation.  Maybe as an option on the generator that can minify / obfuscate the whole thing with short names and minimum white space etc.  Just the white space would maybe be worth 30%

Also since I'm not sure the best way to contact you, and didnt want to generate an issue to ask a question.  I found the logDebug function, but it always treats my String text as a long.  I have been using the logException to get String based console.log output.  Is there a better trick?

**Comment by mirkosertic** [comment]
Well, I think if there are open questions, feel free to open a new issue about each one. Then answers can be easily tracked and found by other users.

About console.log :  try `de.mirkosertic.bytecoder.api.web.Console.console().log(message)`
