### ISSUE TITLE
Create a ready to use docker Bytecoder docker container 

### ISSUE THREAD

**Issue by ccinelli** [mirkosertic/Bytecoder#158]
Some projects just provide a ready-to-use Docker image that dramatically simplify usage reducing it to one line in shell.

In the case of `bytecoder`, you could simplify everything having a docker container that can be used to compile a java project in a folder with just a line of docker. 

Check for example https://hub.docker.com/r/trzeci/emscripten/ and https://github.com/trzecieu/emscripten-docker

**Comment by ccinelli** [comment]
And this is a lot simpler example: https://github.com/jborza/docker-closure-compiler

**Comment by mirkosertic** [comment]
This project assumes Developer who know Java and its ecosystem, and have a working SDK and Maven/Gradle Toolchain available. I really don't see the usecase to run a Docker container from within Maven oder the IDE, just for the compilation step. For this purpose, the Maven Plugin was created.

Adding another layer of indirection around the CLI or Maven would not make the things easier. #126 assumes users who don't know Java, Maven and SDK installations. It would be a lot easier for those users learn the required tools instead of hoping other tools they have to learn(docker) keep them away from learning what is happing.

**Comment by ccinelli** [comment]
Right, now Bytecoder assume deeper knowledge on the Java ecosystem.  

There are a few advantages of a docker image that compile Java code to WebAssembly:

1) Projects that relay on Java code to be compiled to webassembly would have an easy way to compile code on a CI environment before deployment in staging or production environments. That is an advantage for both people familiar and not familiar with Java. We use the closure compiler image to minimize some JS code for example.

2) People that are not too familiar with the Java ecosystem that may want to use some functions from a Java library  (Ex: `boofcv`) would have a lower barrier to do it.

**Comment by mirkosertic** [comment]
The Bytecoder CLI can be easily used. This Issue is closed due to no further user feedback.
