### ISSUE TITLE
Create a Gradle Plugin

### ISSUE THREAD

**Issue by mirkosertic** [mirkosertic/Bytecoder#159]

**Comment by WhiteHexagon** [comment]
Since I last contacted you I switched from Java to Kotlin, and finally got a bit of free time to port my demo over.  The code is ported, but then I realised I have no way in gradle (using kotlin kts) to call the plugin.  So +1 and looking forward to testing your new plugin!  assuming Kotlin hasn't completely mangled the byte code...

**Comment by mirkosertic** [comment]
Sounds good! I don't think the Kotlin Bytecode is too mangled, Bytecoder has a working Kotlin Example. Unfortunately this exampe is build with Maven, so we have to wait for a proper Gradle plugin.
Of course, if you like, you can submit a PR for this feature :-)

**Comment by mirkosertic** [comment]
https://guides.gradle.org/writing-gradle-plugins/

**Comment by WhiteHexagon** [comment]
hah, yes, I did consider that tonight, and I already had a look at what was involved :) and found your maven plugin code I was going to try and port, but then I found your CLI...  great :)  So I just delegate to that for now.  Although so far it didnt work, so maybe I will try again at the weekend with something simpler, since I have quite a few top level functions and extended classes.  I am using CLI 2019-06-13, but my kotlin code is using still using 2019-03-22, since I wanted to try with something I already had working.  Anyway I get a null pointer exception CompileTarget.java:83

**Comment by WhiteHexagon** [comment]
I just quickly tried the newer 2019-06-29 and same NPE.

**Comment by mirkosertic** [comment]
Hmm, that NPE shouldNät be there, I fixed that for the latest release.
Basically this NPE means that there is no entry method found. The current release should provide a clearer message here.

**Comment by WhiteHexagon** [comment]
OK that was a good clue! :)  kotlin allows main to have no args declared main ie fun main() vs fun main(args: <Array>String).  Adding the args got me a bit further...  

Caused by: java.lang.RuntimeException: Error linking class kotlin.jvm.internal.Intrinsics
        at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.resolveClass(BytecodeLinkerContext.java:111)
 ...
Caused by: java.lang.ClassNotFoundException: kotlin/jvm/internal/Intrinsics.class
        at de.mirkosertic.bytecoder.core.BytecodeLoader.loadByteCode(BytecodeLoader.java:56)

btw using Kotlin version 1.3.21-release-158

So for that I included in the claspath the kotlin-stdlib.jar.  I read that including the runtime should help, but I couldnt find a jar for only the runtime.  Anyway now I am hitting ClassNotFoundException: Main.  But maybe it is looking in the wrong jar, since my app is also a jar on the classpath...  I try again tomorrow.

**Comment by WhiteHexagon** [comment]
fyi it fails in CLI at line 103: classLoader.loadClass(theCLIOptions.mainClass)
In my jar I see Main.class and Main$main$1.class 
and running it like this: 
java -jar bytecoder-cli-2019-06-13-executable.jar -classpath=kotlin-stdlib.jar:./build/libs/art.jar -mainclass=Main -builddirectory=build -backend=wasm -minify=false

**Comment by WhiteHexagon** [comment]
So I changed the .kts to generate a fat jar.  That gets me a bit further.  Now it fails at:

at de.mirkosertic.bytecoder.backend.wasm.WASMWriterUtils.toClassNameInternal(WASMWriterUtils.java:78)

 String thePackageName = aClassName.substring(0, p);

This looks like it might be related to not having a package name in my kotlin project, since it seems to be looking for punkt . in the name.

**Comment by WhiteHexagon** [comment]
So I can confirm that a package name is required for main, and the wasm is now generated.  The wasm file has jumped from 28KB to 550KB though and fails to load with the browser console showing:

CompileError: wasm validation error: at offset 2980: memory size minimum must not be greater than maximum; maximum length 0 is less than initial length 512

**Comment by objectProgrammer** [comment]
Hello, I have created a plugin for this: https://github.com/objectProgrammer/BytecoderGradle

@mirkosertic Can you check it out and see if I did anything incorrect and if possible add a link to it in the User Manual?

**Comment by mirkosertic** [comment]
@objectProgrammer your plugin looks very promising. It seems to be implemeted correctly.
However, would you like to contribute the sources to the Bytecoder repository? The CompileOptions API is subject of changes sometimes(#234), and this will break the plugin. By integrating both repositories we could create some CI tests and only release if it compiles and is working.

**Comment by objectProgrammer** [comment]
@mirkosertic I created an updated branch at https://github.com/objectProgrammer/BytecoderGradle/tree/a540964 but it's not a good method and can cause confusion. I have a question, since the plugin is a Gradle project but Bytecoder is a maven one, how would you reference the latest snapshot (parent) from within the Gralde plugin (without the use of JitPack)?

**Comment by mirkosertic** [comment]
@objectProgrammer I'd like to fulle integrate the sources from your Gradle plugin into the Bytecoder repository as a separate module under the APLv2 license. The plugin would therefore be bound to the Bytecoder release cycle and be distributed by Maven central under the de.mirkosertic.bytecoder groupId. Would that be ok for you?

**Comment by mirkosertic** [comment]
This issue is closed due to lack of priority.

**Comment by objectProgrammer** [comment]
@mirkosertic I'm not sure why you don't want it to be GPL but okay. I have no problems with transferring the project as long as I get to keep write permissions and credit in either an "@author" javadoc tag or a "Copyright" comment.

**Comment by mirkosertic** [comment]
@objectProgrammer of course you will be marked as the author of the code. Unfortunately I cannot give you write permissions to the repository. So I will not integrate your code into the Bytecoder repository. Sorry.

**Comment by objectProgrammer** [comment]
@mirkosertic Okay, but I think a separate repository will be better because I'm not sure if you can mix Maven and Gradle. However, if you think that it'll work, being able to contribute through pull requests (and javadoc/copyright credit) will be enough for me.

**Comment by objectProgrammer** [comment]
@mirkosertic So?

**Comment by mirkosertic** [comment]
If you like, you can file a PR for Bytecoder including a new Maven module producing the Gradle plugin. This should be feasible, I think. If everything is well, the Documentation needs an update, too.

I think the best way is to use a single repo with a single release process. There are sometimes breaking changes in the Bytecoder Tool API, and we can only track this by compiling the Plugin and Bytecoder core together.

**Comment by objectProgrammer** [comment]
I don't think that it is possible to compile a Gradle plugin using Maven. Gradle has some internal stuff for that.

**Comment by mirkosertic** [comment]
I'm pretty sure we just need a dependency to the gradle api and a property file mentioning the implementation-class. All of this can be done with Maven.

However, I don't have time to implement all of this. Your PR will be very welcome, but Maven has to be used as it is the project build management tool. If this cannot be done however, I think this ticket will remain in closed state.

**Comment by objectProgrammer** [comment]
https://stackoverflow.com/questions/59522350/gradle-plugin-dependency

I'm afraid this will remain closed then. It seems a little too complicated for me as I haven't used maven that much, and including a gradle-api jar isn't a good solution either.
