### ISSUE TITLE
Dynamic linking generation

### ISSUE THREAD

**Issue by Karang** [mirkosertic/Bytecoder#26]
We could add a new Annotation to set a javascript implementation of a function when we declare it:
```java
@Import(module = "webglcontext", name = "viewport")
@JSImpl("function(ref, x, y, width, height) {" + 
        "    webglCtx[ref].viewport(x, y, width, height);" + 
        "}")
public native void viewport(int x, int y, int width, int height);
```
This way the compiler could generate a lib_module.js for each module containing only the linked functions.
We could also place the anotation on the Class to provide a way to initialize a context (instances list) :
```java
@JSImpl("var webglBuffer = [];" + 
        "var webglCtx = [];" + 
	"var webglFramebuffer = [];" + 
	"var webglProgram = [];" + 
	"var webglRenderbuffer = [];" + 
	"var webglRenderingContext = [];" + 
	"var webglShader = [];" + 
	"var webglShaderPrecisionFormat = [];" + 
	"var webglTexture = [];" + 
	"var webglUniformLoc = [];")
public class WebGLRenderingContext {
```
It would be easier for the library and api developpers to have all the code in one place.
The annotation could be optional, but then it is the responsability of the user to provide the implementations in the js wrapper.

**Comment by mirkosertic** [comment]
Ok, I understand your concerns about usability for library developers. Thank you for this issue.

Let me explain the reasoning for the initial design of the `@Import` and `@Export` functionalities. 

`@Import` marks a external usage depency. We import an external defined code and just use it. All implementation details are provided at linking time. These dependencies can be anything, another WASM module or other ES6- style modules.

`@Export` marks an implemented functionality as ready for use by external parties. This functionality can be linked to other WASM or ES6-style modules.

Since `@Import` marks a usage and not a implementation dependency, I don't know if it would be good to mix it with some kind of inlined JavaScript. We'd loose all kind of compile time checks for the JS code. Maybe I'd be good to provide the JS implementation code by either ES6 JS or TypeScript and compile this to Browser-Ready-JS with proper module loading. This way, we could still use JS compile time checking and keep the def-use-separation ready. Of course this indirection would add a little bit overhead for API developers. What do you think?

**Comment by norzak** [comment]
Do we have JSImp or something similar in the codebase (de/mirkosertic/bytecoder/api)? I could not see one. How do we define the body of the native method?

**Comment by norzak** [comment]
We should be able to produce a single JavaScript file (merged) as well (which our system requires in some use cases), something like JSImp or JSBody for a native method implementation is a must I think or at least must be optional for the developers. This is also good for encapsulating development to a single homogeneous source base instead of heterogeneous one.

**Comment by mirkosertic** [comment]
See #69 and #70

**Comment by mirkosertic** [comment]
I think most of the problems can be solved using the new Opaque Types API, so there is no need to add JS Annotations to existing Bytecode. Also the new API works greatly with WASM output.

**Comment by mirkosertic** [comment]
Issue closed due to lack of feedback.
