### ISSUE TITLE
Errors in multiple String concatenation

### ISSUE THREAD

**Issue by Karang** [mirkosertic/Bytecoder#27]
Hi, I found a bug (not that easy to reproduce) in the String concatenation:
```java
public static String getOne() {
	return "1";
}

public static String getTwo() {
	return "2";
}

public static String getThree() {
	return "3";
}
	
public static void main(String[] args) {
	System.out.println(">"+getOne()+","+getTwo()+","+getThree()+"<");
}
```
Gives : ">3,2,1<" (wrong order)
I tracked the bug in webassembly to the moment the array contening the arguments of TStringConcatFactory.makeConcatWithConstants is constructed (Object[] args) : 
```
(i32.store offset=44 (get_local $SP)
             (call $MemoryManager_AddressnewArrayINTINTINT (i32.const 0)                  (i32.const 3) (get_global $TArray__runtimeClass) (i32.const 85)) ;; new array of type de.mirkosertic.bytecoder.core.BytecodeObjectTypeRef@c2861ce2
         
         )
         ;; setting local variable with type INT with value of type INT
         (set_local $var7
             (i32.const 0)         
         )
         (i32.store offset=20 
             (i32.add (i32.load offset=44 (get_local $SP)) (i32.mul (get_local $var7) (i32.const 4)))
             (i32.load offset=32 (get_local $SP))
         )
         ;; setting local variable with type INT with value of type INT
         (set_local $var8
             (i32.const 1)         
         )
         (i32.store offset=20 
             (i32.add (i32.load offset=44 (get_local $SP)) (i32.mul (get_local $var8) (i32.const 4)))
             (i32.load offset=28 (get_local $SP))
         )
         ;; setting local variable with type INT with value of type INT
         (set_local $var9
             (i32.const 2)         
         )
         (i32.store offset=20 
             (i32.add (i32.load offset=44 (get_local $SP)) (i32.mul (get_local $var9) (i32.const 4)))
             (i32.load offset=4 (get_local $SP))
         )
```
Where $SP+4 contains the result from getOne(), $SP+20 the result from getTwo() and $SP+32 the result of getThree()

I would fix it myself but I did'nt found where in the compiler this code is generated (is it taken from the java bytecode as it ?)

Also, there is another bug related : if instead of String the results of getOne, getTwo or getThree are of type int, there is a out of bound error at runtime. Maybe the function treat the content of the array as objects adresses even if they are only simple int.

**Comment by Karang** [comment]
I fixed the ordering bug, the arguments were added in reverse because of the aHelper stack : 
```java
for (int i=theInitSignature.getArguments().length-1;i>=0;i--) {
    Variable theIndex = aTargetBlock.newVariable(TypeRef.Native.INT, new IntegerValue(i));
    aTargetBlock.addExpression(new ArrayStoreExpression(TypeRef.Native.REFERENCE, theArray, theIndex, aHelper.pop()));
 }
```
I'm now looking for the "out of bound" one. I'm suspecting it is due to the fact that the array is an array of references.
I'll make a PR when everything is fixed.

**Comment by mirkosertic** [comment]
Ah, very good, you found the right place to fix it! Most of the time the problem can be found in either `NaiveProgramGenerator` or the JRE emulation classlib. My first guess was that there is a bug in the receipe handling of `TStringConcatFactory`, but it seems indeed be a bug in the program generator.

The program generator translates the JVM bytecode into the internal intermediate representation, which is used for further optimizations and later translated into JS or WAT(WASM).

String concatenation is done since Java 9 using the JVM invoke dynamic semantics and the TStringConcatFactory. Java 8 bytecode used StringBuilder instances instead. See https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-6.html#jvms-6.5.invokedynamic for the invoke dynamic specification. I think the proper object casting and conversion must be done in TStringConcatFactory during interpretation of the concat receipe.
