### ISSUE TITLE
string in native method are not converted to real strings

### ISSUE THREAD

**Issue by blackbirdone** [mirkosertic/Bytecoder#294]
Hello :)

Maybe i do something wrong so here is an example of the problem.
If you have something like that 

`public native get(String id); and want to overwrite it with native js code`

```
getString: function(id) {}
```
Than the string "id" is converted to an array of charcodes you need to decode yourself maybe with something like that
`String.fromCharCode(id.value.data);` id.value.data because thats an array object? its not a plain array you can just throw in

Thats not an easy solution and not really expected.

Okay but if we just do that and enable the minify function the whole JS breaks because the methods on objects are renamed. So the minify function is useless for projects were you have to overwrite native stuff with pure js? or i missing something?

I maybe i  can use the google CL to minify the code to solve the second problem. So maybe that's not an issue for you, if you don't want to care about that or i just missing something :)

I think its related to the issue #165 

kind regards

**Comment by objectProgrammer** [comment]
First of all, are you using WebAssembly? If so then the "id" is not the string. You need to add another parameter and then use bytecoder.toJSString(parameter); If you're not using WebAssembly then I don't know but you can try calling toJSString on the "id".

**Comment by mirkosertic** [comment]
Strings are currently not autuoatically converted from and to JS for performance reasons.

See https://mirkosertic.github.io/Bytecoder/chapter-1/page-1-f/

and as @objectProgrammer stated:

`
java.lang.String references are a special case. They are objects in the sense of the JVM, but they are not automatically converted to JavaScript String instances on host side due to the expensive conversion operation and its potential performance impact. However, there are handy conversion operations available to do it if its really needed. The conversion functions are part of the global bytecoder object as bytecoder.toJSString(aBytecoderString) and bytecoder.toBytecoderString(aJSString) respectively.
`

The process is the same for `JS` and `Wasm`backend.

**Comment by blackbirdone** [comment]
Thanks for your answers :)

Okay, than this is maybe only an issue if you work with String heavily on javascript site.
Its not a problem to convert the objects to real strings on javascript site but it is something you need to aware about.

Would it be possible to convert them to real strings on native method calls. I think its not necessary to convert them all the time, but for native calls its seems that you need to convert them anyway on the JS site. so the performance is not a problem, maybe it is possible to do it with an annotation?

I have something in mind:

```
BYTECODER CODE 

parameter = bytecoder.toJSString(aBytecoderString);
      result = doSomeThingNativeMethod(parameter)
result  = bytecoder.toByteCoderString(result);

BYTECODER CODE 
```

It takes the same amount of resources to do it before the native call or in the native call. Maybe is something that can be relevant. Bytecoder knows already that the nativecall is overwritten with JS anyway. (and it crash if you don't do it)
Than the javascript code would be clean from the code site, you don't need to know that the code is transpiled.

**Comment by objectProgrammer** [comment]
This would cause inconsistency with the WASM backend as in there the wasmbindings.js cannot know a method's parameter type. If you want that feature then I believe it's not too hard to implement it by yourself, you don't even need to modify bytecoder source code, I believe.

**Comment by mirkosertic** [comment]
@blackbirdone the only case were string types are converted automatically are invocations of opaque reference types. Such types are used to access browser APIs like `window` or `document`. The corresponding adapter code is generated automatically. For `normal` native method invocations such conversion must be implemented by hand because of mentioned performance reasons.

So your proposal is already implemented, but just for opaque reference types.

**Comment by mirkosertic** [comment]
Closed due to no further feedback.
