### ISSUE TITLE
Error linking class java.lang.ref.Reference

### ISSUE THREAD

**Issue by frankbauer** [mirkosertic/Bytecoder#72]
Hi.
Great work on this project!

I tried to use the following sample code:
`System.out.println(java.lang.System.getSecurityManager());`

This generates the following error:

> Failed to execute goal de.mirkosertic.bytecoder:bytecoder-mavenplugin:2018-11-29:compile (default) on project ecompile: Error running bytecoder: Cannot find static method getSecurityManager in java/lang/System wizh signature java.lang.SecurityManager() 

Do I miss something in my setup, or isn't it supposed to work?

**Comment by mirkosertic** [comment]
Thank you for this issue! 

Well, Bytecoder uses OpenJDK 11 classlib for bytecode compilation. However, the original OpenJDK classes can sometimes not be used directly because of native code dependencieds and other topics that prevent direct compilation to JS or WebAssembly. Those dependencies needs to be resolved by *shadowing* specific methods or complete classes. 

The java.lang.System class is a great example for this shadowing. You can see the shadowed class in action here: https://github.com/mirkosertic/Bytecoder/blob/master/classlib/java.base/src/main/java/de/mirkosertic/bytecoder/classlib/java/lang/TSystem.java.

So, to make your example working, we need to add SecurityManager support. Also please note that any kind of ReflectionAPI is currently not supported by Bytecoder.

If you like, create new unit test by just copying an existing one in the core Maven modue and try to modify the shadow types till compilation passes. PRs and contrinutions are always welcome!
