### ISSUE TITLE
Add dependencies for maven 

### ISSUE THREAD

**Issue by ansjain83** [mirkosertic/Bytecoder#732]
I would like to use  external decencies like 'org.json' , added to maven but getting following error while running 'mvn clean install'
Failed to execute goal de.mirkosertic.bytecoder:bytecoder-mavenplugin:2021-11-02:compile (default) on project com.test.webassembly: Error running bytecoder: Cannot find virtual method getPackage in non-abstract class java/lang/Class with signature java.lang.Package() -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by mirkosertic** [comment]
Hi!

Thank you for using Bytecoder!

JSON  unmarshalling support implemented by third party libraries like GSON etc. is currently not fully supported and implemented, due to some missing JPMS APIs in Bytecoder and very limited reflection support due to AOT compilation.

Sorry, thats the way it is. There is no quick fix available.

Mirko

**Comment by mirkosertic** [comment]
See also #733

**Comment by mirkosertic** [comment]
Closed due to no further feedback.
